"""Detect drift between a vendored generated API client and its committed snapshot.

A vendored generated client is regenerated by hand from a producer service's
OpenAPI spec. When the producer changes shape and nobody regenerates, the
committed client goes stale and fails at runtime. This checker turns that
silent staleness into a red build: it regenerates the client from the
committed OpenAPI snapshot (the contract-of-record) into a temp dir and diffs
the result against the committed ``generated/`` tree. A non-empty diff is
drift.

The regen mirrors the SDK's ``scripts/regen.sh`` generate+format invocation
(against the committed snapshot rather than live) — same ``openapi-python-client``
flags, same post-generation ``ruff format`` — and runs inside the SDK's own
``uv`` environment so the generator and ``ruff`` versions are pinned by that
SDK's lockfile (a shared/floating toolchain would yield spurious formatting
diffs). ``regen.sh`` writes both the snapshot and the tree from the live
producer, so running it leaves this check a no-op.

This is a hermetic, PR-blocking consistency gate. It does NOT detect drift of
the snapshot itself vs the live producer: a skipped regen after a producer API
change leaves snapshot and tree *consistently* stale, and this hermetic gate
passes. That gap is covered separately by a live-drift guard (see the
vendoring-openapi-client skill's references/live-drift.md).

Usage::

    python scripts/check_client_drift.py [CLIENT ...]   # check (default: all)
    python scripts/check_client_drift.py --write CLIENT  # regen committed tree from snapshot

Exit: 0 no drift · 1 drift · 2 regen/format error.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

# Directory names that are build/cache artifacts, never part of the contract.
IGNORE_DIRS = {"__pycache__", ".ruff_cache"}

# Upper bound for a single regen/format step (cold CI includes a uv sync). A
# bounded wait turns a hung generator into a clear error instead of a stuck job.
_SUBPROCESS_TIMEOUT = 300


class DriftCheckError(RuntimeError):
    """A regen/format subprocess failed — distinct from detected drift."""


@dataclass(frozen=True)
class Client:
    """A vendored generated client and the snapshot it must stay consistent with."""

    name: str
    sdk_dir: Path  # SDK package root (holds pyproject.toml + uv.lock + scripts/regen.sh)
    generated_dir: Path  # committed generated tree, the diff target
    spec_path: Path  # committed OpenAPI snapshot the tree is regenerated from


# Registry of vendored clients this repo carries. EDIT ME: one entry per
# vendored SDK, following the template below. The vendoring-openapi-client
# skill fills this in when it wires a new client.
#
# _EXAMPLE_SDK = REPO_ROOT / "clients" / "<producer>-python"
#
# CLIENTS: dict[str, Client] = {
#     "<producer>": Client(
#         name="<producer>",
#         sdk_dir=_EXAMPLE_SDK,
#         generated_dir=_EXAMPLE_SDK / "src" / "<producer>_client" / "generated",
#         spec_path=_EXAMPLE_SDK / "<producer>-openapi.json",
#     ),
# }
CLIENTS: dict[str, Client] = {}


def _relative_files(root: Path) -> dict[str, Path]:
    """Map POSIX-relative path → file Path for every non-ignored file under ``root``."""
    result: dict[str, Path] = {}
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(root)
        if any(part in IGNORE_DIRS for part in rel.parts):
            continue
        result[rel.as_posix()] = path
    return result


def diff_trees(expected: Path, actual: Path) -> list[tuple[str, str]]:
    """Compare two generated trees and return a sorted list of drift entries.

    Each entry is ``(status, relpath)`` where ``status`` is:

    - ``"changed"`` — present in both but bytes differ
    - ``"only_in_actual"`` — produced by the fresh regen but missing from the
      committed tree (the committed client is stale)
    - ``"only_in_expected"`` — in the committed tree but no longer produced
      (upstream removed it)

    ``expected`` is the committed tree, ``actual`` the fresh regen. Files under
    ``__pycache__``/``.ruff_cache`` are ignored. An empty list means no drift.
    """
    exp = _relative_files(Path(expected))
    act = _relative_files(Path(actual))
    drift: list[tuple[str, str]] = []
    for rel in set(exp) | set(act):
        in_exp, in_act = rel in exp, rel in act
        if in_exp and in_act:
            if exp[rel].read_bytes() != act[rel].read_bytes():
                drift.append(("changed", rel))
        elif in_act:
            drift.append(("only_in_actual", rel))
        else:
            drift.append(("only_in_expected", rel))
    return sorted(drift, key=lambda entry: (entry[1], entry[0]))


def _run(cmd: list[str], *, cwd: Path) -> None:
    """Run a regen/format step, surfacing failures as ``DriftCheckError``.

    ``capture_output`` keeps the generator's noise off CI logs on success; on
    failure the captured stdout/stderr is folded into the raised message so the
    real error is visible instead of a bare ``CalledProcessError`` traceback.
    """
    try:
        subprocess.run(
            cmd,
            cwd=cwd,
            check=True,
            capture_output=True,
            text=True,
            timeout=_SUBPROCESS_TIMEOUT,
        )
    except subprocess.CalledProcessError as e:
        raise DriftCheckError(
            f"command failed (exit {e.returncode}): {' '.join(cmd)}\n"
            f"--- stdout ---\n{e.stdout}\n--- stderr ---\n{e.stderr}"
        ) from e
    except subprocess.TimeoutExpired as e:
        raise DriftCheckError(
            f"command timed out after {_SUBPROCESS_TIMEOUT}s: {' '.join(cmd)}"
        ) from e


def _regenerate(client: Client, dest: Path) -> None:
    """Regenerate ``client`` from its snapshot into ``dest``, mirroring regen.sh.

    Runs inside the SDK's own ``uv`` environment (``cwd=sdk_dir``) so the pinned
    generator and ``ruff`` versions are used. ``dest`` MUST live inside the SDK
    tree: ``ruff`` discovers its config by walking up from each formatted file,
    and only an in-tree path resolves the same ``pyproject.toml`` that regen.sh
    uses. (A path outside the SDK falls back to ruff's default config, which
    wraps borderline imports the committed tree leaves on one line — spurious
    drift.) ``check_client`` and ``write_client`` both pass in-tree paths.
    """
    _run(
        [
            "uv",
            "run",
            "openapi-python-client",
            "generate",
            "--path",
            str(client.spec_path),
            "--meta",
            "none",
            "--output-path",
            str(dest),
            "--overwrite",
        ],
        cwd=client.sdk_dir,
    )
    _run(["uv", "run", "ruff", "format", str(dest)], cwd=client.sdk_dir)


@contextmanager
def _regenerate_in_tree(client: Client) -> Iterator[Path]:
    """Regenerate ``client`` into an in-tree temp dir; yield the generated path.

    The temp dir lives inside the SDK tree so ``ruff`` resolves the same config
    regen.sh does (see ``_regenerate``); it is removed on exit.
    """
    with tempfile.TemporaryDirectory(dir=client.sdk_dir, prefix=".drift-") as tmp:
        dest = Path(tmp) / "generated"
        _regenerate(client, dest)
        yield dest


def check_client(client: Client) -> list[tuple[str, str]]:
    """Regenerate ``client`` from its snapshot into a temp dir and diff vs committed."""
    with _regenerate_in_tree(client) as dest:
        return diff_trees(client.generated_dir, dest)


def write_client(client: Client) -> None:
    """Regenerate the committed tree from the snapshot (drift remediation).

    Regenerates into an in-tree staging dir first and only swaps it into place
    once generation succeeds, so a mid-regen failure cannot leave the committed
    tree deleted.
    """
    with _regenerate_in_tree(client) as staging:
        if client.generated_dir.exists():
            shutil.rmtree(client.generated_dir)
        shutil.copytree(
            staging,
            client.generated_dir,
            ignore=shutil.ignore_patterns(*IGNORE_DIRS),
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "clients",
        nargs="*",
        choices=sorted(CLIENTS),
        help="clients to check (default: all)",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate the committed tree(s) from the snapshot in place, then exit",
    )
    args = parser.parse_args(argv)
    if not CLIENTS:
        print(
            "ERROR: no clients registered — fill in the CLIENTS registry in this script",
            file=sys.stderr,
        )
        return 2
    names = args.clients or sorted(CLIENTS)

    if args.write:
        for name in names:
            try:
                write_client(CLIENTS[name])
            except DriftCheckError as e:
                print(f"ERROR: could not write {name} client: {e}", file=sys.stderr)
                return 2
            print(f"wrote: {CLIENTS[name].generated_dir.relative_to(REPO_ROOT)}")
        return 0

    any_drift = False
    for name in names:
        client = CLIENTS[name]
        try:
            drift = check_client(client)
        except DriftCheckError as e:
            print(f"ERROR: could not check {name} client: {e}", file=sys.stderr)
            return 2
        if not drift:
            print(f"OK: {name} client matches {client.spec_path.name}")
            continue
        any_drift = True
        print(f"DRIFT: {name} client is stale vs {client.spec_path.name}")
        for status, rel in drift:
            print(f"  {status:16} {rel}")
        # Two distinct causes need opposite fixes:
        rel_regen = (client.sdk_dir / "scripts" / "regen.sh").relative_to(REPO_ROOT)
        print(
            "  → hand-edited generated/? discard edits, regenerate from the snapshot:\n"
            f"      python scripts/check_client_drift.py --write {name}"
        )
        print(
            f"  → {name} legitimately changed upstream? refresh snapshot + tree together:\n"
            f"      bash {rel_regen}"
        )
        print("    (then commit)")
    return 1 if any_drift else 0


if __name__ == "__main__":
    sys.exit(main())
