#!/usr/bin/env bash
# run-integration-tests.sh
# The billed suite, run by hand. Never wired to a gate: pre-commit's pre-push
# integration hook is commented out (LLM non-determinism), and scripts/pre-ship.sh
# deliberately does not call this.
#
# Usage: bash scripts/run-integration-tests.sh [--help] [pytest args...]
set -euo pipefail

usage() {
  echo "Usage: bash \"$0\" [--help] [pytest args...]"
  echo ""
  echo "Runs tests/integration/ with -m integration. BILLED (~\$0.16 for a full"
  echo "run) and needs ANTHROPIC_API_KEY, which it loads from .env at the repo"
  echo "root (or a legacy bare 'env' file) by parsing it line by line."
  echo ""
  echo "Options:"
  echo "  --help   Show this text and exit 0, spending nothing."
  echo ""
  echo "Any other arguments are forwarded to pytest, e.g. -k <expr> to run one"
  echo "test instead of the suite."
  echo ""
  echo "Exit codes:"
  echo "  0  the suite passed"
  echo "  1  test failures"
  echo "  2  no usable .venv at the repo root, or not inside a git repository"
  echo "  5  pytest collected no tests — not a pass; check -m/-k and the path"
  echo "  *  otherwise pytest's own exit code, passed through unchanged"
}

# --help must never reach pytest. Until #318 this script forwarded nothing and
# handled nothing, so `--help` was silently dropped and the BILLED suite ran —
# the one flag a reader tries first in order to find out what a script costs.
if [[ "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

# Everything below is relative — the .env probe, .venv and tests/integration/ —
# so resolve the root rather than trusting the caller's cwd. Without this, a run
# from a subdirectory reported "no usable .venv at the repo root" about a repo
# root whose .venv was fine (CR 4).
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
  echo "ERROR: not inside a git repository — the suite did not run." >&2
  exit 2
}
cd "$REPO_ROOT"

# Export vars from the secrets file if present (provides ANTHROPIC_API_KEY etc.).
# `.env` is the cohort-wide name; bare `env` is the name this repo used before
# 2026-08-05 and is accepted so an older checkout still runs.
#
# Parsed, not sourced, and read line by line: the previous `export $(xargs < env)`
# word-split every value, so a key containing a space or a `#` comment on the line
# silently exported the wrong thing — and sourcing would execute whatever the file
# contained.
for _envfile in .env env; do
  [ -f "$_envfile" ] || continue
  while IFS= read -r _line || [ -n "$_line" ]; do
    case "$_line" in
      ''|\#*) continue ;;
    esac
    _line="${_line#export }"
    case "$_line" in
      *=*) ;;
      *) continue ;;
    esac
    _name="${_line%%=*}"
    _val="${_line#*=}"
    case "$_name" in
      ''|*[!A-Za-z0-9_]*) continue ;;
    esac
    # Strip one layer of matching quotes and any trailing CR from a CRLF file.
    _val="${_val%$'\r'}"
    case "$_val" in
      \"*\") _val="${_val#\"}"; _val="${_val%\"}" ;;
      \'*\') _val="${_val#\'}"; _val="${_val%\'}" ;;
    esac
    export "$_name=$_val"
  done <"$_envfile"
  break
done

if [[ ! -e ".venv/bin/activate" ]]; then
  echo "ERROR: no usable .venv at the repo root — the suite cannot run." >&2
  echo "  Create it:  python3 -m venv .venv && source .venv/bin/activate" >&2
  echo "              pip install -r requirements-test.txt" >&2
  echo "  In a linked worktree:  ln -s <main-checkout>/.venv .venv" >&2
  exit 2
fi

# Generated by `python -m venv`, so there is nothing in the repo for shellcheck
# to follow; whether it resolves would otherwise depend on the caller's cwd.
# shellcheck source=/dev/null
source .venv/bin/activate
# `exec` replaces this shell, so pytest's exit code IS this script's — see the
# usage block. "$@" carries any pytest args through; --help was intercepted above.
exec pytest tests/integration/ -v -m integration "$@"
